Spring:
  application:
    name: springboot-products-api
  datasource:
    url: jdbc:h2:mem:products
    username: sa
    password: password
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
      console:
        enabled: true
        path: /h2-console